//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrecheApplication.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activity()
        {
            this.ChildActivity = new HashSet<ChildActivity>();
            this.UserActivity = new HashSet<UserActivity>();
        }
        public Activity(string photo, string description)
        {
            this.Photo = photo;
            this.Name = description;
        }

        public Activity(int activityId, string photo, string description)
        {
            this.ActivityID = activityId;
            this.Photo = photo;
            this.Name = description;
        }

        public int ActivityID { get; set; }
        public string Photo { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> dayDate { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChildActivity> ChildActivity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserActivity> UserActivity { get; set; }
    }
}
