//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrecheApplication.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CrecheEntities : DbContext
    {
        public CrecheEntities()
            : base("name=CrecheEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Child> Child { get; set; }
        public virtual DbSet<ChildSchedule> ChildSchedule { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<Food> Food { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<ChildActivity> ChildActivity { get; set; }
        public virtual DbSet<ChildFood> ChildFood { get; set; }
        public virtual DbSet<UserActivity> UserActivity { get; set; }
    }
}
