//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrecheApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserActivity
    {
        public int UserActivityID { get; set; }
        public Nullable<int> Fk_User { get; set; }
        public Nullable<int> Fk_Activity { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual User User { get; set; }
    }
}
